export const SCOPE_FUNCTION = 1, SCOPE_ASYNC = 2, SCOPE_GENERATOR = 4, SCOPE_ARROW = 8, SCOPE_SIMPLE_CATCH = 16

export const BIND_NONE = 0, BIND_VAR = 1, BIND_LEXICAL = 2, BIND_FUNCTION = 3, BIND_SIMPLE_CATCH = 4, BIND_OUTSIDE = 5
